### ISSUE TITLE
Handle singular/plural confusion in countdown readout

### ISSUE THREAD

**Issue by ErikBoesen** [ErikBoesen/Yalebot#15]

**Comment by kchen1250** [comment]
https://github.com/ErikBoesen/Yalebot/pull/79

**Comment by ErikBoesen** [comment]
@kchen1250  In the future, you can write "Fix #79" in the body of the PR and it will automatically close the issue when the PR is merged.

**Comment by kchen1250** [comment]
Oh, did not know this. Thanks!
