### ISSUE TITLE
Auto correct college names 

### ISSUE THREAD

**Issue by AAgar** [ErikBoesen/Yalebot#9]
University of Chicago - UC Hicago
Stanford - "Stanford"
Harvard -UMass Cambridge or 🅱️arvard
Penn - Wharton + small LAC

And some others

**Comment by ErikBoesen** [comment]
I really wish GroupMe allowed editing messages, that would make it really fun.

**Comment by AAgar** [comment]
I don't mean editing messages, just responding with "Did you mean: ____"

**Comment by ErikBoesen** [comment]
Oh yeah, I know, it would be neat though.
